server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/plain

  servlet:
    context-path: /api

spring:
  application:
    name: api-libraryBook

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  flyway:
    enabled: TRUE
    locations: classpath:db/migration
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql