management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always

server:
  port: 8081
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: application/json,application/xml,text/html,text/plain

  servlet:
    context-path: /api

info:
  application:
    groupId: '@project.groupId@'
    artifactId: '@project.artifactId@'
    version: '@project.version@'

spring:
  application:
    name: api-libraryBook

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true

  flyway:
    enabled: TRUE
    locations: classpath:db/migration
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql